
version: "3"

services:
  db:
    image: mysql:8.0.36
    container_name: db
    networks:
    - wordpress-net
    env_file: ../.env.db
    volumes:
      - "db_vol:/var/lib/mysql"


  wordpress:
    networks:
    - wordpress-net
    - lb
    depends_on:
      - db
    build:
      context: ./wordpress
      dockerfile: Dockerfile

    environment:
      WORDPRESS_DB_HOST: "db:3306"
    env_file: ../.env.wordpress
    volumes:
      - "wp_vol:/var/www/html"

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - db
      - wordpress
    volumes:
      - wp_vol:/var/www/html
    ports:
      - "8080:80"
    networks:
      - lb

volumes:
  db_vol:
  wp_vol:

networks:
  wordpress-net:
  lb:
