
version: "3"

services:

  db:
    image: mysql:8.0.36
    container_name: db
    networks:
    - wordpress-net
    env_file: ../.env.db
    volumes:
      - "db_vol:/var/lib/mysql"

  newrelic-php-daemon:
    image: newrelic/php-daemon
    container_name: newrelic-php-daemon
    networks:
      - newrelic-net

  wordpress:
    depends_on:
      - db
      - newrelic-php-daemon
    build:
      context: ./wordpress
      dockerfile: Dockerfile
      args:
        NEW_RELIC_AGENT_VERSION: "10.10.0.1"
        NEW_RELIC_LICENSE_KEY: "u01xxe98521b693b4b6740e69d2c552FFFFNRAL"
        NEW_RELIC_APPNAME: "wordpress-php"
        IMAGE_NAME: "wordpress:php8.1-fpm"
    container_name: wordpress
    networks:
      - wordpress-net
      - lb
      - newrelic-net
    env_file: ../.env.wordpress
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    volumes:
      - "wp_vol:/var/www/html"

  webserver:
    depends_on:
    - wordpress
    image: nginx:alpine3.18
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
    - lb
    container_name: webserver
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "wp_vol:/var/www/html"

volumes:
  db_vol:
  wp_vol:

networks:
  wordpress-net:
  lb:
  newrelic-net:
