
version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: db
    networks:
    - wordpress-net
    environment:
      MYSQL_ROOT_PASSWORD: "23e2dR#@e3E#E{}"
      MYSQL_USER: "rtcamp"
      MYSQL_PASSWORD: "dipankar"
      MYSQL_DATABASE: "wordpress"
    volumes:
      - "./db_vol:/var/lib/mysql"

  wordpress:
    depends_on:
      - db
    image: wordpress:fpm
    container_name: wordpress
    networks:
    - wordpress-net
    - lb
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: "rtcamp"
      WORDPRESS_DB_PASSWORD: "dipankar"
      WORDPRESS_DB_NAME: "wordpress"
    volumes:
      - "./wp_vol:/var/www/html"

  webserver:
    depends_on:
      - db
      - wordpress
    image: nginx:latest
    ports:
      - "80:80"
    networks:
    - lb
    container_name: webserver
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./wp_vol:/var/www/html"

networks:
  wordpress-net:
  lb:
