
version: "3.8"

services:
  db:
    image: mysql:latest
    user: "${USERID}:${GROUPID}"
    container_name: db
    networks:
    - wordpress-net
    environment:
      MYSQL_ROOT_PASSWORD: "23e2dR#@e3E#E{}"
      MYSQL_USER: "rtcamp"
      MYSQL_PASSWORD: "dipankar"
      MYSQL_DATABASE: "wordpress"
    volumes:
      - type: bind
        source: "/ee/db_vol"
        target: "/var/lib/mysql"

  wordpress:
    depends_on:
      - db
    image: wordpress:fpm
    user: "${USERID}:${GROUPID}"
    container_name: wordpress
    networks:
    - wordpress-net
    - lb
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: "rtcamp"
      WORDPRESS_DB_PASSWORD: "dipankar"
      WORDPRESS_DB_NAME: "wordpress"
    volumes:
      - type: bind
        source: "/ee/wp_vol"
        target: "/var/www/html"

  webserver:
    depends_on:
      - db
      - wordpress
    image: nginx:latest
    user: "${USERID}:${GROUPID}"
    ports:
      - "80:80"
    networks:
    - lb
    container_name: webserver
    volumes:
      - type: bind
        source: "nginx.conf"
        target: "/etc/nginx/conf.d/default.conf"
      - type: bind
        source: "/ee/wp_vol"
        target: "/var/www/html"

networks:
  wordpress-net:
  lb:
