
version: "3"

services:
  db:
    image: mysql:8.0.36
    container_name: db
    restart: unless-stopped
    networks:
    - wordpress-net
    env_file: ../.env.db
    volumes:
      - "db_vol:/var/lib/mysql"

  wordpress:
    depends_on:
      - db
    restart: unless-stopped
    image: wordpress:php8.1-fpm-alpine
    container_name: wordpress
    networks:
    - wordpress-net
    - lb
    env_file: ../.env.wordpress
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    volumes:
      - "wp_vol:/var/www/html"

  webserver:
    depends_on:
      certbot:
        condition: service_completed_successfully

    image: nginx:alpine3.18
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
    - lb
    container_name: webserver
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "wp_vol:/var/www/html"
      - "certbot_vol:/etc/letsencrypt"

  certbot:
    image: certbot/certbot
    restart: on-failure
    volumes:
      - certbot_vol:/etc/letsencrypt

    ports:
      - "80:80"
    command: ['certonly', '--standalone', '--agree-tos', '--staging', '--email','dipankar.das@rtcamp.com', '-d', 'dipankar.rt.gw']
    # command: ['certonly', '--standalone', '--agree-tos', '--email','dipankar.das@rtcamp.com', '-d', 'dipankar.rt.gw']

    healthcheck:
      test: ["CMD-SHELL", "ls -la /etc/letsencrypt/live/dipankar.rt.gw/fullchain.pem || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

volumes:
  db_vol:
  wp_vol:
  certbot_vol:

networks:
  wordpress-net:
  lb:
