
version: "3"

services:
  db:
    image: mysql:8.0.36
    container_name: db
    networks:
    - wordpress-net
    env_file: ../.env.db
    volumes:
      - "db_vol:/var/lib/mysql"

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1-fpm-alpine
    container_name: wordpress
    networks:
    - wordpress-net
    - lb
    env_file: ../.env.wordpress
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    volumes:
      - "wp_vol:/var/www/html"

  webserver:
    depends_on:
      pre_certbot:
        condition: service_completed_successfully

    image: nginx:alpine3.18
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
    - lb
    container_name: webserver
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "wp_vol:/var/www/html"
      - "certbot_vol:/etc/letsencrypt"

  pre_certbot:
    image: ubuntu
    volumes:
      - wp_vol:/var/www/html
      - "certbot_vol:/etc/letsencrypt"
    command:
    - /bin/bash
    - -c
    - |
      echo "create acme-challenge folders"
      mkdir -p /var/www/html/.well-known/acme-challenge
      chown -R 82:www-data /var/www/html/.well-known/acme-challenge

      echo "create temporary certificates so that nginx is running"
      mkdir -p /etc/letsencrypt/live/dipankar.rt.gw
      cd /etc/letsencrypt/live/dipankar.rt.gw
      apt update -y
      apt install openssl -y
      openssl req -x509 -nodes -newkey rsa:4096 -days 1 -keyout 'privkey.pem' -out 'fullchain.pem' -subj '/CN=localhost'
    depends_on:
    - wordpress

    healthcheck:
      test: ["CMD-SHELL", "ls -la /etc/letsencrypt/live/dipankar.rt.gw/fullchain.pem || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

  certbot:
    image: certbot/certbot
    depends_on:
      pre_certbot:
        condition: service_completed_successfully
    restart: on-failure
    volumes:
      - _certbot_vol:/etc/letsencrypt  # using a new volume to again write the contents back
      - wp_vol:/var/www/html  # directly to nginx
    command: ['certonly', '--webroot', '--webroot-path=/var/www/html','--agree-tos', '--force-renewal','--email','dipankar.das@rtcamp.com','-d', 'dipankar.rt.gw']

    healthcheck:
      test: ["CMD-SHELL", "ls -la /etc/letsencrypt/live/dipankar.rt.gw/fullchain.pem || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    
  post_certbot:
    image: ubuntu
    depends_on:
      certbot:
        condition: service_completed_successfully
    volumes:
      - certbot_vol:/etc/letsencrypt
      - _certbot_vol:/etc/_letsencrypt
    command:
    - '/bin/bash'
    - '-c'
    - |
      echo "#######"
      ls -laR /etc/_letsencrypt
      echo "#######"
      ls -laR /etc/letsencrypt
      mv -v /etc/_letsencrypt/etc/letsencrypt/live /etc/letsencrypt/live

volumes:
  db_vol:
  wp_vol:
  _certbot_vol:
  certbot_vol:

networks:
  wordpress-net:
  lb:
