
version: "3"

services:
  db:
    image: mysql:8.0.36
    container_name: db
    networks:
    - wordpress-net
    env_file: ../.env.db
    volumes:
      - "db_vol:/var/lib/mysql"

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1-fpm-alpine
    container_name: wordpress
    networks:
    - wordpress-net
    - lb
    env_file: ../.env.wordpress
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    volumes:
      - "wp_vol:/var/www/html"

  webserver:
    depends_on:
      - wordpress
    image: nginx:alpine3.18
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
    - lb
    container_name: webserver
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "wp_vol:/var/www/html"
      - "certbot_vol:/etc/letsencrypt"

  # certbot:
  #   depends_on:
  #     - webserver
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot_vol:/etc/letsencrypt
  #     - wp_vol:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email dipankar.das@rtcamp.com --force-renewal --agree-tos --no-eff-email -d dipankar.rt.gw
  permissions:
    image: ubuntu
    volumes:
      - wp_vol:/var/www/html
    command:
    - /bin/bash
    - -c
    - |
      mkdir -p /var/www/html/.well-known/acme-challenge
      chown -R 82:www-data /var/www/html/.well-known/acme-challenge
      ls -lRa /var/www/html/
    
  certbot:
    image: certbot/certbot
    depends_on:
      - webserver
      - permissions
    restart: unless-stopped
    volumes:
      - certbot_vol:/etc/letsencrypt
      - wp_vol:/var/www/html
    command: ['certonly', '--webroot', '--webroot-path=/var/www/html','--agree-tos', '--email','dipankar0115@gmail.com','-d', 'dipankar.rt.gw']  # Replace with your domain
    

volumes:
  db_vol:
  wp_vol:
  certbot_vol:

networks:
  wordpress-net:
  lb:
