
version: "3"

services:
  db:
    image: mysql:8.0.36
    container_name: db
    networks:
    - wordpress-net
    env_file: ../.env.db
    volumes:
      - "db_vol:/var/lib/mysql"

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1-fpm-alpine
    container_name: wordpress
    networks:
    - wordpress-net
    - lb
    env_file: ../.env.wordpress
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    volumes:
      - "wp_vol:/var/www/html"

  webserver:
    depends_on:
      - wordpress
      - pre-certbot
    image: nginx:alpine3.18
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    networks:
    - lb
    container_name: webserver
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "wp_vol:/var/www/html"
      - "certbot_vol:/etc/letsencrypt"

  permissions:
    image: ubuntu
    volumes:
      - wp_vol:/var/www/html
    command:
    - /bin/bash
    - -c
    - |
      mkdir -p /var/www/html/.well-known/acme-challenge
      chown -R 82:www-data /var/www/html/.well-known/acme-challenge
      ls -lRa /var/www/html/

  pre-certbot:
    image: certbot/certbot
    depends_on:
      - permissions
      - webserver
    restart: on-failure
    volumes:
      - certbot_vol:/etc/letsencrypt
      - wp_vol:/var/www/html
    command: ['certonly', '--webroot', '--webroot-path=/var/www/html','--agree-tos', '--staging','--email','dipankar.das@rtcamp.com','-d', 'dipankar.rt.gw']
    
  certbot:
    image: certbot/certbot
    depends_on:
      - webserver
      - pre-certbot
    restart: on-failure
    volumes:
      - certbot_vol:/etc/letsencrypt
      - wp_vol:/var/www/html
    command: ['certonly', '--webroot', '--webroot-path=/var/www/html','--agree-tos', '--force-renewal','--email','dipankar.das@rtcamp.com','-d', 'dipankar.rt.gw']
    

volumes:
  db_vol:
  wp_vol:
  certbot_vol:

networks:
  wordpress-net:
  lb:
